import { Inter } from "next/font/google";
import { Montserrat } from "next/font/google";
import Sidebar from "./componentes/SideBar";
import Header from "./componentes/Header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Perfil de Usuario",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header></Header>
        {children}
        <Sidebar></Sidebar>
      </body>
    </html>
  );
}
